// Passos do tutorial geral do dashboard (tutorial/tutorial.js).
// img: arquivo em tutorial/img (servido só com login via /api/tutorial-img).
// spot: destaque em % da imagem (1440x820). view: aba que o botão "Abrir esta tela" abre;
// passo com view que o usuário não tem permissão de ver é pulado automaticamente.
// Capturado das telas reais em 05/10/2026. Mudou uma tela? Recapture a imagem e revise o texto.
window.TUT_DATA = [
 { img:'t01.jpg', spot:{x:0,y:20.05,w:16.03,h:79.95}, tag:'Navegação', titulo:'O menu do site',
   texto:'Todas as telas ficam no <b>menu da esquerda</b>, agrupadas por assunto: <b>Dotações</b>, <b>Saúde Capex</b>, <b>Materiais</b>, <b>FP&amp;A</b>, <b>Fiscalização</b>, <b>Segurança</b>, <b>Planejamento</b> e <b>Frota</b>. Os números ao lado de cada item mostram quantos registros ou pendências existem ali. Cada pessoa vê só as telas que tem permissão de acessar.' },
 { img:'t02.jpg', spot:{x:5.14,y:12.68,w:92.42,h:10.63}, tag:'Visão Geral', titulo:'Filtre por ano, PEP, empresa e squad', view:'overview',
   texto:'A barra de filtros do topo vale para as telas de dotações. Cada filtro tem <b>caixas de seleção e pesquisa</b>: digite parte do nome e marque só o que interessa. <b>Limpar</b> volta tudo para "Todos".' },
 { img:'t02.jpg', spot:{x:5.14,y:26.49,w:92.42,h:25.6}, tag:'Visão Geral', titulo:'O resumo financeiro em uma tela', view:'overview',
   texto:'Os cards trazem <b>Dotações</b>, <b>CAPEX contratado</b>, <b>Medido total</b>, <b>Irregularidades</b> e <b>Materiais</b>. Logo abaixo, <b>Ações necessárias</b> mostra dotações estouradas, irregularidades de CAPEX e sub-PEPs críticos: clique em um deles para abrir a lista já filtrada.' },
 { img:'t02.jpg', spot:{x:3.33,y:0.73,w:96.67,h:11.2}, tag:'Topo', titulo:'Status ao vivo e exportação', view:'overview',
   texto:'A faixa <b>LIVE</b> mostra que os dados estão sincronizados, se há filtro ativo e <b>quem está online</b>. No canto direito você troca o tema (claro ou escuro) e exporta a tela atual em <b>PDF</b>, <b>CSV</b> ou <b>Excel</b>.' },
 { img:'t03.jpg', spot:{x:6.6,y:26.5,w:89.3,h:24}, tag:'Dotações', titulo:'Resumo por Sub PEP', view:'resumo',
   texto:'Dotado, medido, saldo e <b>% comprometido</b> acumulados por empresa e sub-PEP. Escolha o <b>mês do medido</b>, filtre só os <b>críticos (75% ou mais)</b> ou <b>estourados (100% ou mais)</b>, e alterne entre <b>Dashboard</b> e <b>Tabela</b>.' },
 { img:'t04.jpg', spot:{x:5.5,y:30.5,w:93,h:48.5}, tag:'Dotações', titulo:'O registro de todas as dotações', view:'dotacoes',
   texto:'Cada linha é uma dotação, com PEP, sub-PEP, empresa, valor solicitado, tipo e <b>status</b> (aprovada, aguardando aprovação ou reprovada). O <b>lápis</b> edita a observação, e o filtro <b>Status</b> aparece só nesta tela.' },
 { img:'t05.jpg', spot:{x:5.3,y:23.5,w:92.5,h:20}, tag:'Dotações', titulo:'Capex Projetos', view:'alertas',
   texto:'O CAPEX de cada projeto comparado com o contratado e o pago: total de linhas, <b>irregularidades</b> (linhas que precisam regularizar), contratado, pago acumulado e <b>desvio</b>. Em <b>Gráficos</b> você vê o avanço por PEP; em <b>Tabela</b>, linha a linha.' },
 { img:'t06.jpg', spot:{x:6.4,y:15,w:89.8,h:14}, tag:'Dotações', titulo:'CJI3: execução mês a mês', view:'cji3',
   texto:'A CJI3 do SAP organizada por <b>Projeto, WBS e Fornecedor</b>, com o valor executado em cada mês. Clique na seta para abrir um projeto, ou use <b>Expandir tudo</b>. Filtre por ano, mês, projeto e empresa. <b>Atualizar arquivo</b> sobe uma CJI3 nova.' },
 { img:'t07.jpg', spot:{x:6.8,y:29.5,w:65.4,h:20.5}, tag:'Dotações', titulo:'Cadastrar uma nova dotação', view:'nova',
   texto:'Escolha primeiro o <b>PEP</b>: a lista de <b>sub-PEPs</b> já vem filtrada para aquele projeto. Depois informe o fornecedor (com busca na base de fornecedores), o valor, o status, o tipo e a observação.' },
 { img:'t08.jpg', spot:{x:5.3,y:30.7,w:93.5,h:12.3}, tag:'Dotações', titulo:'Regularizar Saldo', view:'regularizar',
   texto:'Cruza o <b>CAPEX medido</b> com as <b>dotações abertas</b>. Saldo negativo vira <b>"Regularizar no CAPEX"</b> (vermelho); saldo positivo aparece como <b>Coberto</b> (verde). Os cards somam o total descoberto e o total coberto.' },
 { img:'t09.jpg', spot:{x:6.8,y:49,w:89,h:49}, tag:'Saúde Capex', titulo:'Dashboard de saúde dos PEPs', view:'analytics',
   texto:'CAPEX total, contratado, pago e a contratar de todos os PEPs. O <b>farol</b> separa os projetos em Normal (abaixo de 80%), Atenção (80 a 99%) e Crítico (100% ou mais), e ao lado está o <b>comprometimento por squad</b>.' },
 { img:'t10.jpg', spot:{x:6.4,y:30.5,w:89.8,h:19.2}, tag:'Saúde Capex', titulo:'Saúde do PEP, projeto a projeto', view:'saude-pep',
   texto:'Um cartão por projeto com o <b>saldo</b> e o farol. Filtre por <b>status</b> (Normal, Atenção, Crítico), grupo, squad, líder ou planejador, e clique no cartão para abrir o detalhe financeiro do projeto.' },
 { img:'t11.jpg', spot:{x:6.8,y:20.5,w:89.5,h:23}, tag:'Materiais', titulo:'Pedidos, RCs e diligenciamento', view:'materiais',
   texto:'Todos os pedidos e RCs da base de Materiais, com fornecedor, situação, previsão de entrega e faturamento. Os filtros começam <b>sem nada marcado</b>, e o contador ao lado mostra quantos itens estão aparecendo do total. Se algum filtro esconder pedidos, aparece um <b>aviso amarelo</b> com o botão <b>Limpar filtros</b>.' },
 { img:'t12.jpg', spot:{x:6.8,y:49,w:89.5,h:33}, tag:'Materiais', titulo:'Projeção de Orçamento', view:'materiais',
   texto:'Na subaba <b>Projeção de Orçamento</b>, marque um ou vários meses para ver quanto está <b>previsto cair</b> (CJI5) e quanto já foi <b>realizado</b> (CJI3), por pedido. Os atalhos (próximo mês, próximos 3, até o fim do ano, atrasados) marcam os meses de uma vez, e a curva de desembolso segue os filtros.' },
 { img:'t13.jpg', spot:{x:7,y:15.5,w:89.8,h:33.5}, tag:'Materiais', titulo:'Pipeline de Materiais', view:'pipe',
   texto:'Acompanha cada LM de <b>Engenharia a Cotação, RC, Aprovação e Pedido</b>, com os dias na etapa atual e a projeção de conclusão. O <b>risco</b> compara essa projeção com a data de necessidade. Use <b>+ Nova LM</b> para incluir e <b>Configurar Prazos</b> para ajustar o prazo de cada etapa.' },
 { img:'t14.jpg', spot:{x:5.3,y:13,w:92.2,h:26.5}, tag:'FP&A', titulo:'Orçamento, executado e forecast', view:'fpa',
   texto:'Importe a <b>planilha FP&amp;A</b> e veja, em dólar, o orçamento, o executado no ano, o forecast e o <b>desvio</b>. A curva S compara os três mês a mês, e na tabela de baixo a linha de projeção de cada projeto é <b>editável</b> (Enter salva).' },
 { img:'t15.jpg', spot:{x:6.5,y:38.3,w:89.5,h:28}, tag:'Fiscalização', titulo:'Produtividade das equipes', view:'improdutividade',
   texto:'Registros de <b>chegada e atraso</b> das equipes em campo: horas produtivas e improdutivas, atraso médio e jornada líquida. Cada número tem um <b>"!"</b> que explica a conta. As abas mostram por empresa, por obra, por squad, a evolução, o RDO diário e o comparativo.' },
 { img:'t16.jpg', spot:{x:6.6,y:39.8,w:90.6,h:31.6}, tag:'Fiscalização', titulo:'Índice de Produtividade', view:'indice-produtividade',
   texto:'Compara o <b>HH cobrado pela contratada</b> com o HH de referência do projeto. Suba o arquivo da contratada, a <b>PQ do Projeto</b> e, se tiver, o catálogo da empresa, ajuste a <b>praticabilidade</b> e clique em <b>Processar comparativo</b>. Os comparativos ficam salvos no <b>Histórico</b>.' },
 { img:'t17.jpg', spot:{x:5.3,y:34.5,w:92.2,h:11.5}, tag:'Segurança', titulo:'Interdições RAC', view:'rac',
   texto:'Importe a planilha de interações do SESuite (uma aba por mês) e veja as ocorrências, as <b>interdições efetivas</b>, o <b>potencial alto (PSIF)</b> e o que está pendente de revisão. Os gráficos mostram o <b>horário</b> das interdições e o ranking por RAC.' },
 { img:'t18.jpg', spot:{x:7.1,y:27.3,w:88.8,h:40}, tag:'Planejamento', titulo:'Histograma CTT', view:'histograma',
   texto:'O <b>efetivo mensal</b> previsto das contratadas, separado em <b>Mecânica, Elétrica e Andaime</b>, com o pico de efetivo e o total de obras. Abaixo, a quantidade de <b>obras ativas</b> em cada mês.' },
 { img:'t19.jpg', spot:{x:7,y:15.5,w:89.8,h:18.5}, tag:'Planejamento', titulo:'SS Milplan', view:'milplan',
   texto:'As <b>Solicitações de Serviço</b> enviadas à Milplan Engenharia, com numeração automática, status (aguardando orçamento, em análise, concluída) e prazo. Filtre por status, squad ou líder, marque <b>Só atrasados</b> ou crie uma com <b>+ Nova SS</b>.' },
 { img:'t20.jpg', spot:{x:7,y:40.5,w:89,h:21.5}, tag:'Frota', titulo:'Telemetria de velocidade', view:'velocidade',
   texto:'Os eventos de excesso de velocidade da frota segundo o Plano de Trânsito: total de eventos, motoristas, tempo em excesso, custo extra estimado e quem vai para o <b>Comitê pela Vida</b>. O destaque vermelho mostra a <b>maior velocidade</b> do período, e a aba <b>Status de Tratamento</b> acompanha cada caso.' },
 { img:'t21.jpg', spot:{x:63.94,y:0.73,w:7.46,h:5.32}, tag:'Pronto', titulo:'Reveja quando quiser',
   texto:'Este tutorial abre sozinho só na primeira vez. Para ver de novo, clique em <b>Tutorial</b> no topo de qualquer tela. Em cada passo, o botão <b>Abrir esta tela</b> leva direto para a tela explicada.' }
];
